name: hspg

dependencies:
  - base
  - ghc
  - ghc-paths
  - template-haskell
  - uniplate

executables:
  hspg-exe:
    main: Main.hs
    dependencies:
      - hspg
      - text

library:
  source-dirs: lib
