name: interpolation-plugin

dependencies:
  - base
  - ghc
  - uniplate

executables:
  interpolation-plugin-example:
    main: Main.hs
    dependencies:
      - interpolation-plugin
      - text

library:
  source-dirs: lib
